PLATFORM_SLUG = 'shein'
PLATFORM_LABEL = 'SHEIN'
SERVER_NAME = 'geekbi-shein-research'
SERVER_TITLE = '极鲸云 SHEIN 数据分析与市场调研'
SERVER_DESCRIPTION = '查询商品、图搜同款、店铺、类目、关键词和评论，研究需求、价格带、竞争、托管模式与用户反馈'
SERVER_INSTRUCTIONS = '这是极鲸云 SHEIN 数据分析服务。根据用户意图选择一个最相关的主工具，仅在结论确需交叉验证时追加其他工具。只依据工具真实返回的数据回答，区分数据事实、可复算指标和分析判断，不编造缺失数据。未指定站点时使用入口 siteId=1；明确美国站使用 siteId=2；其他市场先查询站点。站点 ID、类目 ID、商品 ID 和店铺 ID 不可猜测。\n\n每次说明查询日期、站点、币种、筛选与排序、实际页数、样本量、命中总数和更新时间。未覆盖全部分页时明确为样本，不外推为全平台或全市场。缺失值显示为空或“-”；数值 0 结合字段来源判断，不自动解释为真实为零。热销不等于低竞争或可盈利。支持商品、图搜、店铺、类目、关键词和评论；不把入口 siteId=1 解释为跨国家聚合。\n\n服务返回 linkUrl、goodsUrl 或 mallUrl 时，用原链接将对象名称写成可点击 Markdown，不自行拼接链接。服务返回 actionRequired 时只展示一级中文 msg 和有效 jumpUrl，然后停止分析；用户完成操作后用完全相同参数重试。普通错误只展示一级中文消息，不暴露令牌、设备码、请求头、原始错误 JSON 或异常栈。\n\n默认输出一句话结论、数据口径、关键证据、机会与风险、下一步验证；用户只要列表时保持简洁。跨对象比较必须统一站点、币种、时间窗和筛选边界。所有日期使用绝对日期。'
RESULT_WINDOW = 10000
TOOL_SPECS = [{'key': 'site_list',
  'kind': 'site',
  'name': 'shein_site_list',
  'title': 'SHEIN 站点查询',
  'description': '实时查询 SHEIN 可用站点、站点 ID 和币种。用户指定非默认市场时先调用；不猜测站点 ID。',
  'model': 'SiteListInput',
  'endpoint': '/api/v1/shein/site/ai-list',
  'fields': []},
 {'key': 'goods_search',
  'kind': 'search',
  'name': 'shein_goods_search',
  'title': 'SHEIN 商品搜索',
  'description': '搜索和筛选 SHEIN 商品，分析价格、销量、销售额、评分、上架时间及当前接口提供的竞争指标。只生成用户所需的最小条件，未覆盖全部分页时明确为样本。',
  'model': 'GoodsSearchInput',
  'fields': [{'name': 'keyword', 'type': 'str', 'description': '名称或关键词；保持用户原始语义', 'max_length': 300},
             {'name': 'catIds', 'type': 'list_int', 'description': '极鲸云类目 ID 列表；必须来自用户或类目工具'},
             {'name': 'siteId', 'type': 'int', 'description': '极鲸云站点 ID', 'default': 1, 'ge': 1},
             {'name': 'page', 'type': 'int', 'description': '页码，从 1 开始', 'default': 1, 'ge': 1},
             {'name': 'size', 'type': 'int', 'description': '每页数量', 'default': 20, 'ge': 1, 'le': 200},
             {'name': 'sort',
              'type': 'literal',
              'description': '排序字段；仅在用户有明确排序意图时使用',
              'values': ['createTime',
                         'daySales',
                         'daySalesRate',
                         'daySold',
                         'daySoldRate',
                         'goodsScore',
                         'mallOpenTime',
                         'mallSold',
                         'maxPrice',
                         'maxSupplyPrice',
                         'medianSupplyPrice',
                         'minPrice',
                         'minSupplyPrice',
                         'monthSales',
                         'monthSalesRate',
                         'monthSold',
                         'monthSoldRate',
                         'onSaleTime',
                         'reviewNum',
                         'sales',
                         'similarNum',
                         'similarNumUpdateTime',
                         'sold',
                         'supplyPrice',
                         'totalSales',
                         'totalSalesRate',
                         'totalSold',
                         'totalSoldRate',
                         'updateTime',
                         'weekSales',
                         'weekSalesRate',
                         'weekSold',
                         'weekSoldRate']},
             {'name': 'order', 'type': 'literal', 'description': '排序方向', 'values': ['asc', 'desc'], 'default': 'desc'},
             {'name': 'blockKeyword', 'type': 'str', 'description': '需要排除的商品关键词', 'max_length': 300},
             {'name': 'daySalesMax', 'type': 'float', 'description': 'daySales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySalesMin', 'type': 'float', 'description': 'daySales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySalesRateMax', 'type': 'float', 'description': 'daySalesRate 上限；只需要上限时单独传入'},
             {'name': 'daySalesRateMin', 'type': 'float', 'description': 'daySalesRate 下限；只需要下限时单独传入'},
             {'name': 'daySoldMax', 'type': 'int', 'description': 'daySold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySoldMin', 'type': 'int', 'description': 'daySold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySoldRateMax', 'type': 'float', 'description': 'daySoldRate 上限；只需要上限时单独传入'},
             {'name': 'daySoldRateMin', 'type': 'float', 'description': 'daySoldRate 下限；只需要下限时单独传入'},
             {'name': 'goodsScoreMax', 'type': 'float', 'description': 'goodsScore 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'goodsScoreMin', 'type': 'float', 'description': 'goodsScore 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'hostingMode', 'type': 'literal', 'description': '托管模式：1 为全托管，2 为半托管', 'values': [1, 2]},
             {'name': 'mallOpenTimeMax', 'type': 'datetime', 'description': 'mallOpenTime 上限；只需要上限时单独传入'},
             {'name': 'mallOpenTimeMin', 'type': 'datetime', 'description': 'mallOpenTime 下限；只需要下限时单独传入'},
             {'name': 'mallSoldMax', 'type': 'int', 'description': 'mallSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'mallSoldMin', 'type': 'int', 'description': 'mallSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'matchMode', 'type': 'str', 'description': '关键词匹配模式'},
             {'name': 'monthSalesMax', 'type': 'float', 'description': 'monthSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSalesMin', 'type': 'float', 'description': 'monthSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSalesRateMax', 'type': 'float', 'description': 'monthSalesRate 上限；只需要上限时单独传入'},
             {'name': 'monthSalesRateMin', 'type': 'float', 'description': 'monthSalesRate 下限；只需要下限时单独传入'},
             {'name': 'monthSoldMax', 'type': 'int', 'description': 'monthSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSoldMin', 'type': 'int', 'description': 'monthSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSoldRateMax', 'type': 'float', 'description': 'monthSoldRate 上限；只需要上限时单独传入'},
             {'name': 'monthSoldRateMin', 'type': 'float', 'description': 'monthSoldRate 下限；只需要下限时单独传入'},
             {'name': 'onSaleTimeMax', 'type': 'datetime', 'description': 'onSaleTime 上限；只需要上限时单独传入'},
             {'name': 'onSaleTimeMin', 'type': 'datetime', 'description': 'onSaleTime 下限；只需要下限时单独传入'},
             {'name': 'priceMax', 'type': 'float', 'description': 'price 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'priceMin', 'type': 'float', 'description': 'price 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'reviewNumMax', 'type': 'int', 'description': 'reviewNum 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'reviewNumMin', 'type': 'int', 'description': 'reviewNum 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'salesMax', 'type': 'float', 'description': 'sales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'salesMin', 'type': 'float', 'description': 'sales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'similarNumMax', 'type': 'int', 'description': 'similarNum 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'similarNumMin', 'type': 'int', 'description': 'similarNum 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'soldMax', 'type': 'int', 'description': 'sold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'soldMin', 'type': 'int', 'description': 'sold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'supplyPriceMax', 'type': 'float', 'description': 'supplyPrice 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'supplyPriceMin', 'type': 'float', 'description': 'supplyPrice 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSalesMax', 'type': 'float', 'description': 'totalSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSalesMin', 'type': 'float', 'description': 'totalSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSoldMax', 'type': 'int', 'description': 'totalSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSoldMin', 'type': 'int', 'description': 'totalSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSalesMax', 'type': 'float', 'description': 'weekSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSalesMin', 'type': 'float', 'description': 'weekSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSalesRateMax', 'type': 'float', 'description': 'weekSalesRate 上限；只需要上限时单独传入'},
             {'name': 'weekSalesRateMin', 'type': 'float', 'description': 'weekSalesRate 下限；只需要下限时单独传入'},
             {'name': 'weekSoldMax', 'type': 'int', 'description': 'weekSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSoldMin', 'type': 'int', 'description': 'weekSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSoldRateMax', 'type': 'float', 'description': 'weekSoldRate 上限；只需要上限时单独传入'},
             {'name': 'weekSoldRateMin', 'type': 'float', 'description': 'weekSoldRate 下限；只需要下限时单独传入'}],
  'endpoint': '/api/v1/shein/goods/ai-search'},
 {'key': 'image_search',
  'kind': 'image',
  'name': 'shein_image_search',
  'title': 'SHEIN 图搜同款',
  'description': '用本地图片、URL、Data URI 或 Base64 图片搜索 SHEIN 视觉同款，并在视觉候选池内叠加商品条件。视觉相似不等于规格、材质或供应链完全相同。',
  'model': 'ImageSearchInput',
  'fields': [{'name': 'image',
              'type': 'str',
              'required': True,
              'description': '图片输入：本地路径、file/http/https 地址、Data URI 或 base64: 前缀；最大 10MB'},
             {'name': 'keyword', 'type': 'str', 'description': '名称或关键词；保持用户原始语义', 'max_length': 300},
             {'name': 'catIds', 'type': 'list_int', 'description': '极鲸云类目 ID 列表；必须来自用户或类目工具'},
             {'name': 'siteId', 'type': 'int', 'description': '极鲸云站点 ID', 'default': 1, 'ge': 1},
             {'name': 'page', 'type': 'int', 'description': '页码，从 1 开始', 'default': 1, 'ge': 1},
             {'name': 'size', 'type': 'int', 'description': '每页数量', 'default': 20, 'ge': 1, 'le': 200},
             {'name': 'sort',
              'type': 'literal',
              'description': '排序字段；仅在用户有明确排序意图时使用',
              'values': ['createTime',
                         'daySales',
                         'daySalesRate',
                         'daySold',
                         'daySoldRate',
                         'goodsScore',
                         'mallOpenTime',
                         'mallSold',
                         'maxPrice',
                         'maxSupplyPrice',
                         'medianSupplyPrice',
                         'minPrice',
                         'minSupplyPrice',
                         'monthSales',
                         'monthSalesRate',
                         'monthSold',
                         'monthSoldRate',
                         'onSaleTime',
                         'reviewNum',
                         'sales',
                         'similarNum',
                         'similarNumUpdateTime',
                         'sold',
                         'supplyPrice',
                         'totalSales',
                         'totalSalesRate',
                         'totalSold',
                         'totalSoldRate',
                         'updateTime',
                         'weekSales',
                         'weekSalesRate',
                         'weekSold',
                         'weekSoldRate']},
             {'name': 'order', 'type': 'literal', 'description': '排序方向', 'values': ['asc', 'desc'], 'default': 'desc'},
             {'name': 'blockKeyword', 'type': 'str', 'description': '需要排除的商品关键词', 'max_length': 300},
             {'name': 'daySalesMax', 'type': 'float', 'description': 'daySales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySalesMin', 'type': 'float', 'description': 'daySales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySalesRateMax', 'type': 'float', 'description': 'daySalesRate 上限；只需要上限时单独传入'},
             {'name': 'daySalesRateMin', 'type': 'float', 'description': 'daySalesRate 下限；只需要下限时单独传入'},
             {'name': 'daySoldMax', 'type': 'int', 'description': 'daySold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySoldMin', 'type': 'int', 'description': 'daySold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySoldRateMax', 'type': 'float', 'description': 'daySoldRate 上限；只需要上限时单独传入'},
             {'name': 'daySoldRateMin', 'type': 'float', 'description': 'daySoldRate 下限；只需要下限时单独传入'},
             {'name': 'goodsScoreMax', 'type': 'float', 'description': 'goodsScore 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'goodsScoreMin', 'type': 'float', 'description': 'goodsScore 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'hostingMode', 'type': 'literal', 'description': '托管模式：1 为全托管，2 为半托管', 'values': [1, 2]},
             {'name': 'mallOpenTimeMax', 'type': 'datetime', 'description': 'mallOpenTime 上限；只需要上限时单独传入'},
             {'name': 'mallOpenTimeMin', 'type': 'datetime', 'description': 'mallOpenTime 下限；只需要下限时单独传入'},
             {'name': 'mallSoldMax', 'type': 'int', 'description': 'mallSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'mallSoldMin', 'type': 'int', 'description': 'mallSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'matchMode', 'type': 'str', 'description': '关键词匹配模式'},
             {'name': 'monthSalesMax', 'type': 'float', 'description': 'monthSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSalesMin', 'type': 'float', 'description': 'monthSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSalesRateMax', 'type': 'float', 'description': 'monthSalesRate 上限；只需要上限时单独传入'},
             {'name': 'monthSalesRateMin', 'type': 'float', 'description': 'monthSalesRate 下限；只需要下限时单独传入'},
             {'name': 'monthSoldMax', 'type': 'int', 'description': 'monthSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSoldMin', 'type': 'int', 'description': 'monthSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSoldRateMax', 'type': 'float', 'description': 'monthSoldRate 上限；只需要上限时单独传入'},
             {'name': 'monthSoldRateMin', 'type': 'float', 'description': 'monthSoldRate 下限；只需要下限时单独传入'},
             {'name': 'onSaleTimeMax', 'type': 'datetime', 'description': 'onSaleTime 上限；只需要上限时单独传入'},
             {'name': 'onSaleTimeMin', 'type': 'datetime', 'description': 'onSaleTime 下限；只需要下限时单独传入'},
             {'name': 'priceMax', 'type': 'float', 'description': 'price 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'priceMin', 'type': 'float', 'description': 'price 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'reviewNumMax', 'type': 'int', 'description': 'reviewNum 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'reviewNumMin', 'type': 'int', 'description': 'reviewNum 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'salesMax', 'type': 'float', 'description': 'sales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'salesMin', 'type': 'float', 'description': 'sales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'similarNumMax', 'type': 'int', 'description': 'similarNum 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'similarNumMin', 'type': 'int', 'description': 'similarNum 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'soldMax', 'type': 'int', 'description': 'sold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'soldMin', 'type': 'int', 'description': 'sold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'supplyPriceMax', 'type': 'float', 'description': 'supplyPrice 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'supplyPriceMin', 'type': 'float', 'description': 'supplyPrice 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSalesMax', 'type': 'float', 'description': 'totalSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSalesMin', 'type': 'float', 'description': 'totalSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSoldMax', 'type': 'int', 'description': 'totalSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSoldMin', 'type': 'int', 'description': 'totalSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSalesMax', 'type': 'float', 'description': 'weekSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSalesMin', 'type': 'float', 'description': 'weekSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSalesRateMax', 'type': 'float', 'description': 'weekSalesRate 上限；只需要上限时单独传入'},
             {'name': 'weekSalesRateMin', 'type': 'float', 'description': 'weekSalesRate 下限；只需要下限时单独传入'},
             {'name': 'weekSoldMax', 'type': 'int', 'description': 'weekSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSoldMin', 'type': 'int', 'description': 'weekSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSoldRateMax', 'type': 'float', 'description': 'weekSoldRate 上限；只需要上限时单独传入'},
             {'name': 'weekSoldRateMin', 'type': 'float', 'description': 'weekSoldRate 下限；只需要下限时单独传入'}],
  'endpoint': '/api/v1/shein/goods/ai-image-search'},
 {'key': 'mall_search',
  'kind': 'search',
  'name': 'shein_mall_search',
  'title': 'SHEIN 店铺搜索',
  'description': '搜索和筛选 SHEIN 店铺，分析经营规模、增长、供给结构和竞争表现。未覆盖全部分页时明确为样本。',
  'model': 'MallSearchInput',
  'fields': [{'name': 'keyword', 'type': 'str', 'description': '名称或关键词；保持用户原始语义', 'max_length': 300},
             {'name': 'catIds', 'type': 'list_int', 'description': '极鲸云类目 ID 列表；必须来自用户或类目工具'},
             {'name': 'siteId', 'type': 'int', 'description': '极鲸云站点 ID', 'default': 1, 'ge': 1},
             {'name': 'page', 'type': 'int', 'description': '页码，从 1 开始', 'default': 1, 'ge': 1},
             {'name': 'size', 'type': 'int', 'description': '每页数量', 'default': 20, 'ge': 1, 'le': 200},
             {'name': 'sort',
              'type': 'literal',
              'description': '排序字段；仅在用户有明确排序意图时使用',
              'values': ['avgPrice',
                         'createTime',
                         'dayFollower',
                         'dayFollowerRate',
                         'dayItemCount',
                         'dayItemCountRate',
                         'daySales',
                         'daySalesRate',
                         'daySold',
                         'daySoldRate',
                         'followerNum',
                         'goodsNum',
                         'mallOpenTime',
                         'mallSales',
                         'mallSold',
                         'mallStar',
                         'monthFollower',
                         'monthFollowerRate',
                         'monthItemCount',
                         'monthItemCountRate',
                         'monthSales',
                         'monthSalesRate',
                         'monthSold',
                         'monthSoldRate',
                         'reviewNum',
                         'totalSales',
                         'totalSold',
                         'updateTime',
                         'weekFollower',
                         'weekFollowerRate',
                         'weekItemCount',
                         'weekItemCountRate',
                         'weekSales',
                         'weekSalesRate',
                         'weekSold',
                         'weekSoldRate']},
             {'name': 'order', 'type': 'literal', 'description': '排序方向', 'values': ['asc', 'desc'], 'default': 'desc'},
             {'name': 'avgPriceMax', 'type': 'float', 'description': 'avgPrice 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'avgPriceMin', 'type': 'float', 'description': 'avgPrice 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayFollowerMax', 'type': 'int', 'description': 'dayFollower 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dayFollowerMin', 'type': 'int', 'description': 'dayFollower 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayFollowerRateMax', 'type': 'float', 'description': 'dayFollowerRate 上限；只需要上限时单独传入'},
             {'name': 'dayFollowerRateMin', 'type': 'float', 'description': 'dayFollowerRate 下限；只需要下限时单独传入'},
             {'name': 'dayItemCountMax', 'type': 'int', 'description': 'dayItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dayItemCountMin', 'type': 'int', 'description': 'dayItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayItemCountRateMax', 'type': 'float', 'description': 'dayItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'dayItemCountRateMin', 'type': 'float', 'description': 'dayItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'daySalesMax', 'type': 'float', 'description': 'daySales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySalesMin', 'type': 'float', 'description': 'daySales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySalesRateMax', 'type': 'float', 'description': 'daySalesRate 上限；只需要上限时单独传入'},
             {'name': 'daySalesRateMin', 'type': 'float', 'description': 'daySalesRate 下限；只需要下限时单独传入'},
             {'name': 'daySoldMax', 'type': 'int', 'description': 'daySold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySoldMin', 'type': 'int', 'description': 'daySold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySoldRateMax', 'type': 'float', 'description': 'daySoldRate 上限；只需要上限时单独传入'},
             {'name': 'daySoldRateMin', 'type': 'float', 'description': 'daySoldRate 下限；只需要下限时单独传入'},
             {'name': 'followerNumMax', 'type': 'int', 'description': 'followerNum 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'followerNumMin', 'type': 'int', 'description': 'followerNum 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'goodsNumMax', 'type': 'int', 'description': 'goodsNum 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'goodsNumMin', 'type': 'int', 'description': 'goodsNum 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'hostingMode', 'type': 'literal', 'description': '托管模式：1 为全托管，2 为半托管', 'values': [1, 2]},
             {'name': 'mallOpenTimeMax', 'type': 'datetime', 'description': 'mallOpenTime 上限；只需要上限时单独传入'},
             {'name': 'mallOpenTimeMin', 'type': 'datetime', 'description': 'mallOpenTime 下限；只需要下限时单独传入'},
             {'name': 'mallSalesMax', 'type': 'float', 'description': 'mallSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'mallSalesMin', 'type': 'float', 'description': 'mallSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'mallSoldMax', 'type': 'int', 'description': 'mallSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'mallSoldMin', 'type': 'int', 'description': 'mallSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'mallStarMax', 'type': 'float', 'description': 'mallStar 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'mallStarMin', 'type': 'float', 'description': 'mallStar 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthFollowerMax', 'type': 'int', 'description': 'monthFollower 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthFollowerMin', 'type': 'int', 'description': 'monthFollower 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthFollowerRateMax', 'type': 'float', 'description': 'monthFollowerRate 上限；只需要上限时单独传入'},
             {'name': 'monthFollowerRateMin', 'type': 'float', 'description': 'monthFollowerRate 下限；只需要下限时单独传入'},
             {'name': 'monthItemCountMax', 'type': 'int', 'description': 'monthItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthItemCountMin', 'type': 'int', 'description': 'monthItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthItemCountRateMax', 'type': 'float', 'description': 'monthItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'monthItemCountRateMin', 'type': 'float', 'description': 'monthItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'monthSalesMax', 'type': 'float', 'description': 'monthSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSalesMin', 'type': 'float', 'description': 'monthSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSalesRateMax', 'type': 'float', 'description': 'monthSalesRate 上限；只需要上限时单独传入'},
             {'name': 'monthSalesRateMin', 'type': 'float', 'description': 'monthSalesRate 下限；只需要下限时单独传入'},
             {'name': 'monthSoldMax', 'type': 'int', 'description': 'monthSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSoldMin', 'type': 'int', 'description': 'monthSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSoldRateMax', 'type': 'float', 'description': 'monthSoldRate 上限；只需要上限时单独传入'},
             {'name': 'monthSoldRateMin', 'type': 'float', 'description': 'monthSoldRate 下限；只需要下限时单独传入'},
             {'name': 'reviewNumMax', 'type': 'int', 'description': 'reviewNum 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'reviewNumMin', 'type': 'int', 'description': 'reviewNum 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSalesMax', 'type': 'float', 'description': 'totalSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSalesMin', 'type': 'float', 'description': 'totalSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSoldMax', 'type': 'int', 'description': 'totalSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSoldMin', 'type': 'int', 'description': 'totalSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekFollowerMax', 'type': 'int', 'description': 'weekFollower 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekFollowerMin', 'type': 'int', 'description': 'weekFollower 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekFollowerRateMax', 'type': 'float', 'description': 'weekFollowerRate 上限；只需要上限时单独传入'},
             {'name': 'weekFollowerRateMin', 'type': 'float', 'description': 'weekFollowerRate 下限；只需要下限时单独传入'},
             {'name': 'weekItemCountMax', 'type': 'int', 'description': 'weekItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekItemCountMin', 'type': 'int', 'description': 'weekItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekItemCountRateMax', 'type': 'float', 'description': 'weekItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'weekItemCountRateMin', 'type': 'float', 'description': 'weekItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'weekSalesMax', 'type': 'float', 'description': 'weekSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSalesMin', 'type': 'float', 'description': 'weekSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSalesRateMax', 'type': 'float', 'description': 'weekSalesRate 上限；只需要上限时单独传入'},
             {'name': 'weekSalesRateMin', 'type': 'float', 'description': 'weekSalesRate 下限；只需要下限时单独传入'},
             {'name': 'weekSoldMax', 'type': 'int', 'description': 'weekSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSoldMin', 'type': 'int', 'description': 'weekSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSoldRateMax', 'type': 'float', 'description': 'weekSoldRate 上限；只需要上限时单独传入'},
             {'name': 'weekSoldRateMin', 'type': 'float', 'description': 'weekSoldRate 下限；只需要下限时单独传入'}],
  'endpoint': '/api/v1/shein/mall/ai-search'},
 {'key': 'category_search',
  'kind': 'search',
  'name': 'shein_category_search',
  'title': 'SHEIN 类目搜索',
  'description': '搜索 SHEIN 类目及市场指标，取得可信类目 ID，研究规模、需求、供给与竞争；类目 ID 不可猜测。',
  'model': 'CategorySearchInput',
  'fields': [{'name': 'keyword', 'type': 'str', 'description': '名称或关键词；保持用户原始语义', 'max_length': 300},
             {'name': 'siteId', 'type': 'int', 'description': '极鲸云站点 ID', 'default': 1, 'ge': 1},
             {'name': 'page', 'type': 'int', 'description': '页码，从 1 开始', 'default': 1, 'ge': 1},
             {'name': 'size', 'type': 'int', 'description': '每页数量', 'default': 20, 'ge': 1, 'le': 200},
             {'name': 'sort',
              'type': 'literal',
              'description': '排序字段；仅在用户有明确排序意图时使用',
              'values': ['avgPrice',
                         'catLevel',
                         'createTime',
                         'dayItemCount',
                         'dayItemCountRate',
                         'dayMallCount',
                         'dayMallCountRate',
                         'daySales',
                         'daySalesRate',
                         'daySold',
                         'daySoldRate',
                         'dsr',
                         'itemCount',
                         'mallCount',
                         'monthItemCount',
                         'monthItemCountRate',
                         'monthMallCount',
                         'monthMallCountRate',
                         'monthSales',
                         'monthSalesRate',
                         'monthSold',
                         'monthSoldRate',
                         'sales',
                         'semiManagedItemCount',
                         'semiManagedMallCount',
                         'sold',
                         'totalSales',
                         'totalSold',
                         'updateTime',
                         'weekItemCount',
                         'weekItemCountRate',
                         'weekMallCount',
                         'weekMallCountRate',
                         'weekSales',
                         'weekSalesRate',
                         'weekSold',
                         'weekSoldRate']},
             {'name': 'order', 'type': 'literal', 'description': '排序方向', 'values': ['asc', 'desc'], 'default': 'desc'},
             {'name': 'avgPriceMax', 'type': 'float', 'description': 'avgPrice 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'avgPriceMin', 'type': 'float', 'description': 'avgPrice 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'catLevel', 'type': 'int', 'description': 'catLevel 查询条件；遵循极鲸云接口字段口径', 'ge': 0, 'le': 10},
             {'name': 'dayItemCountMax', 'type': 'int', 'description': 'dayItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dayItemCountMin', 'type': 'int', 'description': 'dayItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayItemCountRateMax', 'type': 'float', 'description': 'dayItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'dayItemCountRateMin', 'type': 'float', 'description': 'dayItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'dayMallCountMax', 'type': 'int', 'description': 'dayMallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dayMallCountMin', 'type': 'int', 'description': 'dayMallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayMallCountRateMax', 'type': 'float', 'description': 'dayMallCountRate 上限；只需要上限时单独传入'},
             {'name': 'dayMallCountRateMin', 'type': 'float', 'description': 'dayMallCountRate 下限；只需要下限时单独传入'},
             {'name': 'daySalesMax', 'type': 'float', 'description': 'daySales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySalesMin', 'type': 'float', 'description': 'daySales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySalesRateMax', 'type': 'float', 'description': 'daySalesRate 上限；只需要上限时单独传入'},
             {'name': 'daySalesRateMin', 'type': 'float', 'description': 'daySalesRate 下限；只需要下限时单独传入'},
             {'name': 'daySoldMax', 'type': 'int', 'description': 'daySold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySoldMin', 'type': 'int', 'description': 'daySold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySoldRateMax', 'type': 'float', 'description': 'daySoldRate 上限；只需要上限时单独传入'},
             {'name': 'daySoldRateMin', 'type': 'float', 'description': 'daySoldRate 下限；只需要下限时单独传入'},
             {'name': 'dsrMax', 'type': 'float', 'description': 'dsr 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dsrMin', 'type': 'float', 'description': 'dsr 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'itemCountMax', 'type': 'int', 'description': 'itemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'itemCountMin', 'type': 'int', 'description': 'itemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'mallCountMax', 'type': 'int', 'description': 'mallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'mallCountMin', 'type': 'int', 'description': 'mallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthItemCountMax', 'type': 'int', 'description': 'monthItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthItemCountMin', 'type': 'int', 'description': 'monthItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthItemCountRateMax', 'type': 'float', 'description': 'monthItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'monthItemCountRateMin', 'type': 'float', 'description': 'monthItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'monthMallCountMax', 'type': 'int', 'description': 'monthMallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthMallCountMin', 'type': 'int', 'description': 'monthMallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthMallCountRateMax', 'type': 'float', 'description': 'monthMallCountRate 上限；只需要上限时单独传入'},
             {'name': 'monthMallCountRateMin', 'type': 'float', 'description': 'monthMallCountRate 下限；只需要下限时单独传入'},
             {'name': 'monthSalesMax', 'type': 'float', 'description': 'monthSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSalesMin', 'type': 'float', 'description': 'monthSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSalesRateMax', 'type': 'float', 'description': 'monthSalesRate 上限；只需要上限时单独传入'},
             {'name': 'monthSalesRateMin', 'type': 'float', 'description': 'monthSalesRate 下限；只需要下限时单独传入'},
             {'name': 'monthSoldMax', 'type': 'int', 'description': 'monthSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSoldMin', 'type': 'int', 'description': 'monthSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSoldRateMax', 'type': 'float', 'description': 'monthSoldRate 上限；只需要上限时单独传入'},
             {'name': 'monthSoldRateMin', 'type': 'float', 'description': 'monthSoldRate 下限；只需要下限时单独传入'},
             {'name': 'parentCatId', 'type': 'int', 'description': '父类目 ID；根节点使用 0', 'ge': 0},
             {'name': 'salesMax', 'type': 'float', 'description': 'sales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'salesMin', 'type': 'float', 'description': 'sales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'semiManagedItemCountMax',
              'type': 'int',
              'description': 'semiManagedItemCount 上限；只需要上限时单独传入',
              'ge': 0},
             {'name': 'semiManagedItemCountMin',
              'type': 'int',
              'description': 'semiManagedItemCount 下限；只需要下限时单独传入',
              'ge': 0},
             {'name': 'semiManagedMallCountMax',
              'type': 'int',
              'description': 'semiManagedMallCount 上限；只需要上限时单独传入',
              'ge': 0},
             {'name': 'semiManagedMallCountMin',
              'type': 'int',
              'description': 'semiManagedMallCount 下限；只需要下限时单独传入',
              'ge': 0},
             {'name': 'soldMax', 'type': 'int', 'description': 'sold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'soldMin', 'type': 'int', 'description': 'sold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSalesMax', 'type': 'float', 'description': 'totalSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSalesMin', 'type': 'float', 'description': 'totalSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSoldMax', 'type': 'int', 'description': 'totalSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSoldMin', 'type': 'int', 'description': 'totalSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekItemCountMax', 'type': 'int', 'description': 'weekItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekItemCountMin', 'type': 'int', 'description': 'weekItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekItemCountRateMax', 'type': 'float', 'description': 'weekItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'weekItemCountRateMin', 'type': 'float', 'description': 'weekItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'weekMallCountMax', 'type': 'int', 'description': 'weekMallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekMallCountMin', 'type': 'int', 'description': 'weekMallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekMallCountRateMax', 'type': 'float', 'description': 'weekMallCountRate 上限；只需要上限时单独传入'},
             {'name': 'weekMallCountRateMin', 'type': 'float', 'description': 'weekMallCountRate 下限；只需要下限时单独传入'},
             {'name': 'weekSalesMax', 'type': 'float', 'description': 'weekSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSalesMin', 'type': 'float', 'description': 'weekSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSalesRateMax', 'type': 'float', 'description': 'weekSalesRate 上限；只需要上限时单独传入'},
             {'name': 'weekSalesRateMin', 'type': 'float', 'description': 'weekSalesRate 下限；只需要下限时单独传入'},
             {'name': 'weekSoldMax', 'type': 'int', 'description': 'weekSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSoldMin', 'type': 'int', 'description': 'weekSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSoldRateMax', 'type': 'float', 'description': 'weekSoldRate 上限；只需要上限时单独传入'},
             {'name': 'weekSoldRateMin', 'type': 'float', 'description': 'weekSoldRate 下限；只需要下限时单独传入'}],
  'endpoint': '/api/v1/shein/category/ai-search'},
 {'key': 'keyword_search',
  'kind': 'search',
  'name': 'shein_keyword_search',
  'title': 'SHEIN 关键词搜索',
  'description': '搜索 SHEIN 关键词及需求供给指标，研究热度、增长和竞争；不能把局部样本表述为全市场。',
  'model': 'KeywordSearchInput',
  'fields': [{'name': 'keyword', 'type': 'str', 'description': '名称或关键词；保持用户原始语义', 'max_length': 300},
             {'name': 'catIds', 'type': 'list_int', 'description': '极鲸云类目 ID 列表；必须来自用户或类目工具'},
             {'name': 'siteId', 'type': 'int', 'description': '极鲸云站点 ID', 'default': 1, 'ge': 1},
             {'name': 'page', 'type': 'int', 'description': '页码，从 1 开始', 'default': 1, 'ge': 1},
             {'name': 'size', 'type': 'int', 'description': '每页数量', 'default': 20, 'ge': 1, 'le': 200},
             {'name': 'sort',
              'type': 'literal',
              'description': '排序字段；仅在用户有明确排序意图时使用',
              'values': ['avgPrice',
                         'createTime',
                         'dayItemCount',
                         'dayItemCountRate',
                         'dayMallCount',
                         'dayMallCountRate',
                         'daySales',
                         'daySalesRate',
                         'daySold',
                         'daySoldRate',
                         'dsr',
                         'firstOnSaleTime',
                         'itemCount',
                         'mallCount',
                         'monthItemCount',
                         'monthItemCountRate',
                         'monthMallCount',
                         'monthMallCountRate',
                         'monthSales',
                         'monthSalesRate',
                         'monthSold',
                         'monthSoldRate',
                         'sales',
                         'semiManagedItemCount',
                         'semiManagedMallCount',
                         'sold',
                         'totalSales',
                         'totalSold',
                         'updateTime',
                         'weekItemCount',
                         'weekItemCountRate',
                         'weekMallCount',
                         'weekMallCountRate',
                         'weekSales',
                         'weekSalesRate',
                         'weekSold',
                         'weekSoldRate']},
             {'name': 'order', 'type': 'literal', 'description': '排序方向', 'values': ['asc', 'desc'], 'default': 'desc'},
             {'name': 'avgPriceMax', 'type': 'float', 'description': 'avgPrice 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'avgPriceMin', 'type': 'float', 'description': 'avgPrice 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayItemCountMax', 'type': 'int', 'description': 'dayItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dayItemCountMin', 'type': 'int', 'description': 'dayItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayItemCountRateMax', 'type': 'float', 'description': 'dayItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'dayItemCountRateMin', 'type': 'float', 'description': 'dayItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'dayMallCountMax', 'type': 'int', 'description': 'dayMallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dayMallCountMin', 'type': 'int', 'description': 'dayMallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'dayMallCountRateMax', 'type': 'float', 'description': 'dayMallCountRate 上限；只需要上限时单独传入'},
             {'name': 'dayMallCountRateMin', 'type': 'float', 'description': 'dayMallCountRate 下限；只需要下限时单独传入'},
             {'name': 'daySalesMax', 'type': 'float', 'description': 'daySales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySalesMin', 'type': 'float', 'description': 'daySales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySalesRateMax', 'type': 'float', 'description': 'daySalesRate 上限；只需要上限时单独传入'},
             {'name': 'daySalesRateMin', 'type': 'float', 'description': 'daySalesRate 下限；只需要下限时单独传入'},
             {'name': 'daySoldMax', 'type': 'int', 'description': 'daySold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'daySoldMin', 'type': 'int', 'description': 'daySold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'daySoldRateMax', 'type': 'float', 'description': 'daySoldRate 上限；只需要上限时单独传入'},
             {'name': 'daySoldRateMin', 'type': 'float', 'description': 'daySoldRate 下限；只需要下限时单独传入'},
             {'name': 'dsrMax', 'type': 'float', 'description': 'dsr 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'dsrMin', 'type': 'float', 'description': 'dsr 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'firstOnSaleTimeMax', 'type': 'datetime', 'description': 'firstOnSaleTime 上限；只需要上限时单独传入'},
             {'name': 'firstOnSaleTimeMin', 'type': 'datetime', 'description': 'firstOnSaleTime 下限；只需要下限时单独传入'},
             {'name': 'itemCountMax', 'type': 'int', 'description': 'itemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'itemCountMin', 'type': 'int', 'description': 'itemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'mallCountMax', 'type': 'int', 'description': 'mallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'mallCountMin', 'type': 'int', 'description': 'mallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthItemCountMax', 'type': 'int', 'description': 'monthItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthItemCountMin', 'type': 'int', 'description': 'monthItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthItemCountRateMax', 'type': 'float', 'description': 'monthItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'monthItemCountRateMin', 'type': 'float', 'description': 'monthItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'monthMallCountMax', 'type': 'int', 'description': 'monthMallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthMallCountMin', 'type': 'int', 'description': 'monthMallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthMallCountRateMax', 'type': 'float', 'description': 'monthMallCountRate 上限；只需要上限时单独传入'},
             {'name': 'monthMallCountRateMin', 'type': 'float', 'description': 'monthMallCountRate 下限；只需要下限时单独传入'},
             {'name': 'monthSalesMax', 'type': 'float', 'description': 'monthSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSalesMin', 'type': 'float', 'description': 'monthSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSalesRateMax', 'type': 'float', 'description': 'monthSalesRate 上限；只需要上限时单独传入'},
             {'name': 'monthSalesRateMin', 'type': 'float', 'description': 'monthSalesRate 下限；只需要下限时单独传入'},
             {'name': 'monthSoldMax', 'type': 'int', 'description': 'monthSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'monthSoldMin', 'type': 'int', 'description': 'monthSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'monthSoldRateMax', 'type': 'float', 'description': 'monthSoldRate 上限；只需要上限时单独传入'},
             {'name': 'monthSoldRateMin', 'type': 'float', 'description': 'monthSoldRate 下限；只需要下限时单独传入'},
             {'name': 'salesMax', 'type': 'float', 'description': 'sales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'salesMin', 'type': 'float', 'description': 'sales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'semiManagedItemCountMax',
              'type': 'int',
              'description': 'semiManagedItemCount 上限；只需要上限时单独传入',
              'ge': 0},
             {'name': 'semiManagedItemCountMin',
              'type': 'int',
              'description': 'semiManagedItemCount 下限；只需要下限时单独传入',
              'ge': 0},
             {'name': 'semiManagedMallCountMax',
              'type': 'int',
              'description': 'semiManagedMallCount 上限；只需要上限时单独传入',
              'ge': 0},
             {'name': 'semiManagedMallCountMin',
              'type': 'int',
              'description': 'semiManagedMallCount 下限；只需要下限时单独传入',
              'ge': 0},
             {'name': 'soldMax', 'type': 'int', 'description': 'sold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'soldMin', 'type': 'int', 'description': 'sold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSalesMax', 'type': 'float', 'description': 'totalSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSalesMin', 'type': 'float', 'description': 'totalSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'totalSoldMax', 'type': 'int', 'description': 'totalSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'totalSoldMin', 'type': 'int', 'description': 'totalSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekItemCountMax', 'type': 'int', 'description': 'weekItemCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekItemCountMin', 'type': 'int', 'description': 'weekItemCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekItemCountRateMax', 'type': 'float', 'description': 'weekItemCountRate 上限；只需要上限时单独传入'},
             {'name': 'weekItemCountRateMin', 'type': 'float', 'description': 'weekItemCountRate 下限；只需要下限时单独传入'},
             {'name': 'weekMallCountMax', 'type': 'int', 'description': 'weekMallCount 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekMallCountMin', 'type': 'int', 'description': 'weekMallCount 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekMallCountRateMax', 'type': 'float', 'description': 'weekMallCountRate 上限；只需要上限时单独传入'},
             {'name': 'weekMallCountRateMin', 'type': 'float', 'description': 'weekMallCountRate 下限；只需要下限时单独传入'},
             {'name': 'weekSalesMax', 'type': 'float', 'description': 'weekSales 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSalesMin', 'type': 'float', 'description': 'weekSales 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSalesRateMax', 'type': 'float', 'description': 'weekSalesRate 上限；只需要上限时单独传入'},
             {'name': 'weekSalesRateMin', 'type': 'float', 'description': 'weekSalesRate 下限；只需要下限时单独传入'},
             {'name': 'weekSoldMax', 'type': 'int', 'description': 'weekSold 上限；只需要上限时单独传入', 'ge': 0},
             {'name': 'weekSoldMin', 'type': 'int', 'description': 'weekSold 下限；只需要下限时单独传入', 'ge': 0},
             {'name': 'weekSoldRateMax', 'type': 'float', 'description': 'weekSoldRate 上限；只需要上限时单独传入'},
             {'name': 'weekSoldRateMin', 'type': 'float', 'description': 'weekSoldRate 下限；只需要下限时单独传入'}],
  'endpoint': '/api/v1/shein/keyword/ai-search'},
 {'key': 'review_search',
  'kind': 'search',
  'name': 'shein_review_search',
  'title': 'SHEIN 商品评论搜索',
  'description': '按明确商品 ID 查询 SHEIN 评论，分析卖点、痛点和规格风险；不能用于全站找商品，也不以单条评论外推。',
  'model': 'ReviewSearchInput',
  'fields': [{'name': 'goodsId',
              'type': 'str',
              'description': '平台商品 ID',
              'max_length': 100,
              'required': True,
              'min_length': 1},
             {'name': 'siteId', 'type': 'int', 'description': '极鲸云站点 ID', 'default': 1, 'ge': 1},
             {'name': 'page', 'type': 'int', 'description': '页码，从 1 开始', 'default': 1, 'ge': 1},
             {'name': 'size', 'type': 'int', 'description': '每页数量', 'default': 20, 'ge': 1, 'le': 200},
             {'name': 'sort',
              'type': 'literal',
              'description': '排序字段；仅在用户有明确排序意图时使用',
              'values': ['commentTime', 'createTime', 'helpful', 'score']},
             {'name': 'order', 'type': 'literal', 'description': '排序方向', 'values': ['asc', 'desc'], 'default': 'desc'},
             {'name': 'commentTimeMax', 'type': 'datetime', 'description': 'commentTime 上限；只需要上限时单独传入'},
             {'name': 'commentTimeMin', 'type': 'datetime', 'description': 'commentTime 下限；只需要下限时单独传入'},
             {'name': 'helpfulMax', 'type': 'int', 'description': '最高有用数', 'ge': 0},
             {'name': 'helpfulMin', 'type': 'int', 'description': '最低有用数', 'ge': 0},
             {'name': 'scoreMax', 'type': 'int', 'description': '最高评论评分，1 至 5 星', 'ge': 1, 'le': 5},
             {'name': 'scoreMin', 'type': 'int', 'description': '最低评论评分，1 至 5 星', 'ge': 1, 'le': 5},
             {'name': 'specs', 'type': 'str', 'description': '评论对应的规格文本', 'max_length': 300}],
  'endpoint': '/api/v1/shein/review/ai-search'}]
